---

- hosts: all
  become: true
  tasks:

  - name: install apache and php support package
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
      update_cache: yes
