---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php support package
    tags: apache2
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package
    tags: mariadb
    package:
      name: mariadb-server
      state: latest

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
